repos:
# ... outros repositórios e hooks

-   repo: https://github.com/antonbabenko/pre-commit-terraform # Ou terraform-docs
    rev: v1.77.0 # Ou a versão mais recente
    hooks:
    -   id: terraform_validate
        args:
          - -json
          - -no-color